---
abstract: 'Makes working with named ip services easier'
author:
  - 'Adam Lesperance <lespea@gmail.com>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Module::Build: '0.3601'
  Test::More: '0.88'
  Test::Most: '0'
  perl: '5.008'
configure_requires:
  File::ShareDir::Install: '0.03'
  Module::Build: '0.3601'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-IANA-Services
no_index:
  directory:
    - inc
    - t
    - xt
    - utils
    - share
    - example
    - examples
  file:
    - README.html
recommends:
  YAML::XS: '0'
requires:
  Exporter::Easy: '0'
  File::ShareDir: '0'
  YAML::Any: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-IANA-Services
  homepage: http://search.cpan.org/dist/Net-IANA-Services
  repository: git://github.com/lespea/net-iana-services.git
version: '0.004000'
x_Dist_Zilla:
  perl:
    version: '5.018002'
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@Author::LESPEA/GatherDir'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@Author::LESPEA/CopyFilesFromBuild'
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::LESPEA/UploadToCPAN'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@Author::LESPEA/ArchiveRelease'
      version: '4.00'
    -
      class: Dist::Zilla::Plugin::AutoMetaResources
      name: '@Author::LESPEA/AutoMetaResources'
      version: '1.20'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::LESPEA/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@Author::LESPEA/Test::Synopsis'
      version: '2.000004'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::LESPEA/PkgVersion'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@Author::LESPEA/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@Author::LESPEA/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Author::LESPEA/prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: EXPORTS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: OPTIONS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: CONSTANTS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Author::LESPEA/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Author::LESPEA/postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::SeeAlso
              name: '@Author::LESPEA/SeeAlso'
              version: '1.002'
            -
              class: Pod::Weaver::Section::Installation
              name: '@Author::LESPEA/Installation'
              version: '1.101421'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Author::LESPEA/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Support
              name: '@Author::LESPEA/Support'
              version: '1.005'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Author::LESPEA/Legal'
              version: '4.006'
            -
              class: Pod::Weaver::Section::WarrantyDisclaimer
              name: '@Author::LESPEA/WarrantyDisclaimer'
              version: '0.121290'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@Author::LESPEA/-Transformer'
              version: '4.006'
      name: '@Author::LESPEA/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@Author::LESPEA/NextRelease'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::LESPEA/MinimumPerl'
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::LESPEA/AutoPrereqs'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::LESPEA/MetaConfig'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@Author::LESPEA/Test::Compile'
      version: '2.040'
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@Author::LESPEA/ConsistentVersionTest'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::LESPEA/Test::Perl::Critic'
      version: '2.112410'
    -
      class: Dist::Zilla::Plugin::Test::DistManifest
      name: '@Author::LESPEA/Test::DistManifest'
      version: '2.000004'
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@Author::LESPEA/HasVersionTests'
      version: '1.101420'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::LESPEA/Test::Kwalitee'
      version: '2.07'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::LESPEA/MetaTests'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::LESPEA/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@Author::LESPEA/Test::NoTabs'
      version: '0.08'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: '@Author::LESPEA/Test::EOL'
      version: '0.12'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::LESPEA/PodCoverageTests'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::LESPEA/PodSyntaxTests'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@Author::LESPEA/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::LESPEA/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::SpellingCommonMistakesTests
      name: '@Author::LESPEA/SpellingCommonMistakesTests'
      version: '1.001000'
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@Author::LESPEA/ExtraTests'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@Author::LESPEA/PruneCruft'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::LESPEA/ManifestSkip'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@Author::LESPEA/ExecDir'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@Author::LESPEA/ShareDir'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@Author::LESPEA/ReportVersions::Tiny'
      version: '1.10'
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::LESPEA/ModuleBuild'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@Author::LESPEA/MakeMaker'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::DualBuilders
      name: '@Author::LESPEA/DualBuilders'
      version: '1.001'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@Author::LESPEA/MetaNoIndex'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::LESPEA/License'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@Author::LESPEA/InstallGuide'
      version: '1.200003'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::LESPEA/MetaJSON'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::LESPEA/MetaYAML'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/html.build'
      version: '0.141120'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/text.build'
      version: '0.141120'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::LESPEA/pod.root'
      version: '0.141120'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::LESPEA/Manifest'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::LESPEA/TestRelease'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::LESPEA/ConfirmRelease'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: Recommends
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - README.pod
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::Check
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: v%v%n%n%c
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - Changes
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Commit_Changes
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: release-0.004000
          tag_format: release-%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::Tag
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - origin
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::Push
      version: '2.022'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.016'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.016'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.016'
x_authority: cpan:LESPEA
